### ISSUE TITLE
Suggestion to improve documentation

### ISSUE THREAD

**Issue by thobach** [stefanjacobs/MMM-Shelly-PM#2]
Thanks for this great project. I have a few suggestions to improve the documentation to avoid installation errors:
* in the config sample of the readme there is a comma missing at "        RefreshInterval: "5000" //milliseconds" 
* in the config sample of the readme I believe the variable should be called"        RefreshIntervalLAN: "5000" //milliseconds" and not "RefreshInterval"
* in the readme there should be a step that after running `git clone` the `npm install` command be run from the `MMM-Shelly-PM ` folder to install "request" dependency that doesn't come with the Magic Mirror app anymore

**Comment by stefanjacobs** [comment]
Thank you. Sorry for the late reply, I will look into this.

**Comment by stefanjacobs** [comment]
Added all your suggestions, thank you for your message (and again sorry for the late reply)
